services:
  etcd:
    image: ${ETCD_IMAGE_VERSION}
    container_name: etcd
    restart: unless-stopped
    ports:
      - '2379:2379'
      - '2380:2380'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    healthcheck:
      test: ['CMD', 'etcdctl', 'endpoint', 'health']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
