services:
  redis:
    image: ${REDIS_IMAGE_VERSION}
    container_name: redis
    command: sh -c "redis-server --appendonly yes --aof-use-rdb-preamble yes"
    restart: unless-stopped
    volumes:
      - ./data/redis_data:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
