services:
  postgres:
    image: ${POSTGRES_IMAGE_VERSION}
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HATCHET_PASSWORD: ${HATCHET_PASSWORD}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./script/postgres_script:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
