services:
  rabbitmq:
    image: ${RABBITMQ_IMAGE_VERSION}
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./data/rabbitmq_data:/var/lib/rabbitmq/
