services:
  loki:
    image: ${LOKI_IMAGE_VERSION}
    command: '-config.file=/etc/loki/config.yaml'
    container_name: loki
    restart: unless-stopped
    ports:
      - 3100:3100
      - 7946
      - 9095
    volumes:
      - ./config/loki_config/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
