services:
  caddy:
    image: ${CADDY_IMAGE_VERSION}
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./config/caddy_config/Caddyfile:/etc/caddy/Caddyfile
      - ./config/caddy_config/site:/srv
      - ./data/caddy_data/data:/data
      - ./data/caddy_data/config:/config
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://127.0.0.1:2019/config/ || exit 1']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
