services:
  consul-server:
    image: ${CONSUL_IMAGE_VERSION}
    container_name: consul-server
    restart: unless-stopped
    volumes:
      - ./config/consul_config/server.json:/consul/config/server.json:ro
      - ./data/consul_data:/consul/data
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    command: 'agent'
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: local-dev
    healthcheck:
      test: ['CMD', 'consul', 'members', '-http-addr=http://localhost:8500']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
